blueprints/szyfry/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SelectField, SubmitField, IntegerField
from wtforms.validators import DataRequired

alphabets = [
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    'AĄBCĆDEĘFGHIJKLŁMNŃOÓPRSŚTUWYZŹŻ',
    'AĄBCĆDEĘFGHIJKLŁMNŃOÓPQRSŚTUVWXYZŹŻ'
]

options_sylabowy = [
    "GADERYPOLUKI",
    "POLITYKARENU",
    "MOTYLECUDAKI",
    "KACEMINUTOWY",
    "KONIECMATURY",
    "NOWEBUTYLISA",
    "MALINOWEBUTY",
    "BITWAOCHMURY",
    "BAWOLETYKIJU",
    "ZIELONYBUK",
    "NASZHUFIEC",
    "GUBIKALESONY",
    "POLEMINEFAGU",
    "PADYGIMOZETU",
    "KULOPERYZAGI",
    "REGULAMINOWY",
    "HALOJUPITERY"
]


class DiacriticsForm(FlaskForm):
    message = TextAreaField(label='Wiadomość:', validators=[DataRequired()], render_kw={"placeholder": "Twoja wiadomość..."})
    submit = SubmitField('Potwierdź')


class CipherForm(FlaskForm):
    message = TextAreaField(label='Wiadomość:', validators=[DataRequired()], render_kw={"placeholder": "Twoja wiadomość..."})
    submit = SubmitField('Potwierdź')
    mode = SelectField(label='Tryb:', choices=['Zaszyfruj', 'Odszyfruj'])


class CezarForm(CipherForm):
    alphabet = SelectField(label='Alfabet:', choices=alphabets)
    move = IntegerField(label='Przesunięcie:', default=3)


class VigenereForm(CipherForm):
    key = TextAreaField(label='Klucz:', render_kw={"placeholder": "Pozostaw pusty, aby wygenerować losowy"})
    alphabet = SelectField(label='Alfabet:', choices=alphabets)


class SylabowyForm(CipherForm):
    mode = SelectField(label='Szyfr: ', choices=options_sylabowy)

blueprints/szyfry/routes.py
from flask import Blueprint, render_template
from unidecode import unidecode
from .forms import CezarForm, CipherForm, VigenereForm, SylabowyForm, DiacriticsForm
from .functions import morse_process, cezar_process, vigenere_process, sylabowy_process


szyfry = Blueprint('szyfry', __name__, template_folder='templates', static_folder='static')
active_tab = "szyfry"


@szyfry.route("/")
def index():
    return render_template("szyfry.html", active_tab=active_tab)


@szyfry.route("/morse", methods=["GET", "POST"])
def morse():
    form = CipherForm()
    message = None
    if form.validate_on_submit():
        message = morse_process(form)
    return render_template("morse.html", active_tab=active_tab, form=form, message=message)


@szyfry.route("/cezar", methods=["GET", "POST"])
def cezar():
    form = CezarForm()
    message = None
    if form.validate_on_submit():
        message = cezar_process(form)
    return render_template("cezar.html", active_tab=active_tab, form=form, message=message)


@szyfry.route("/vigenere", methods=["GET", "POST"])
def vigenere():
    form = VigenereForm()
    message = None
    if form.validate_on_submit():
        message, form.key.data = vigenere_process(form)
    return render_template("vigenere.html", active_tab=active_tab, form=form, message=message)


@szyfry.route("/sylabowy", methods=["GET", "POST"])
def sylabowy():
    form = SylabowyForm()
    message = None
    if form.validate_on_submit():
        message = sylabowy_process(form)
    return render_template("sylabowy.html", active_tab=active_tab, form=form, message=message)


@szyfry.route("/remove-diacritics", methods=["GET", "POST"])
def diacritics():
    form = DiacriticsForm()
    message = None
    if form.validate_on_submit():
        message = unidecode(form.message.data)
    return render_template("diacritics.html", active_tab=active_tab, form=form, message=message)

blueprints/szyfry/templates/cezar.html
{% extends "szyfry.html" %}
{% block form %}
<div id="morse">
    <h2>Szyfr Cezara</h2>
    <form method="POST", action="{{ url_for('szyfry.cezar') }}">
        {{ form.csrf_token }}
        {{ form.message.label }} <br>
        {{ form.message }}
        {{ form.alphabet.label }} {{ form.alphabet }} <br>
        {{ form.move.label }} {{ form.move(style="width:45px;") }} <br>
        {{ form.mode.label }} {{ form.mode }} <br>

        {{ form.submit }}
    </form>
</div>
{% endblock %}

blueprints/szyfry/templates/diacritics.html
{% extends "szyfry.html" %}
{% block form %}
<div id="morse">
    <h2>Usuń znaki diakrytyczne</h2>
    <form method="POST", action="{{ url_for('szyfry.diacritics') }}">
        {{ form.csrf_token }}
        {{ form.message.label }} <br>
        {{ form.message }}
        {{ form.submit }}
    </form>
</div>
{% endblock %}

blueprints/szyfry/templates/morse.html
{% extends "szyfry.html" %}
{% block form %}
<div id="morse">
    <h2>Alfabet Morse'a</h2>
    <form method="POST", action="{{ url_for('szyfry.morse') }}">
        {{ form.csrf_token }}
        {{ form.message.label }} <br>
        {{ form.message }}
        {{ form.mode.label }} {{ form.mode }} <br>
        {{ form.submit }}
    </form>
</div>
{% endblock %}

blueprints/szyfry/templates/sylabowy.html
{% extends "szyfry.html" %}
{% block form %}
<div id="morse">
    <h2>Szyfr Sylabowy</h2>
    <form method="POST", action="{{ url_for('szyfry.sylabowy') }}">
        {{ form.csrf_token }}
        {{ form.message.label }} <br>
        {{ form.message }}
        {{ form.mode.label }} {{ form.mode }} <br>
        {{ form.submit }}
    </form>
</div>
{% endblock %}

blueprints/szyfry/templates/szyfry.html
{% extends "base.html" %}


{% block css %}
<link rel="stylesheet" href="{{ url_for('.static', filename='css/style.css') }}">
{% endblock %}


{% block title %}Szyfry{% endblock %}


{% block content %}

    <h1>Szyfry</h1>
    <a class="button" href="{{ url_for('szyfry.morse' )}}">Morse</a>
    <a class="button" href="{{ url_for('szyfry.cezar' )}}">Cezar</a>
    <a class="button" href="{{ url_for('szyfry.vigenere') }}">Vigenère</a>
    <a class="button" href="{{ url_for('szyfry.sylabowy') }}">Sylabowy</a>
    <a class="button" href="{{ url_for('szyfry.diacritics') }}">Usuń diakrytyki</a>

    {% block form %}{% endblock %}

    {% if message %}
        <div class="card">
            <div id="message_card">{{ message }}</div> 
        </div>
        <input type="submit" class="" onclick="copyMessage()" value="Kopiuj do schowka">
    {% endif %}    
    
    <script>
        function copyMessage() {
            var copyText = document.getElementById("message_card");
            navigator.clipboard.writeText(copyText.textContent);
        }
    </script>
{% endblock %}

blueprints/szyfry/templates/vigenere.html
{% extends "szyfry.html" %}
{% block form %}
<div id="morse">
    <h2>Szyfr Viegenère'a</h2>
    <form method="POST", action="{{ url_for('szyfry.vigenere') }}">
        {{ form.csrf_token }}
        {{ form.message.label }} <br>
        {{ form.message }}
        {{ form.key.label }} <br>
        {{ form.key }}
        {{ form.alphabet.label }} {{ form.alphabet }} <br>
        {{ form.mode.label }} {{ form.mode }} <br>

        {{ form.submit }}
    </form>
</div>
{% endblock %}